Dev/nat theotokos antiphon1
JedBartlett/OrthodoxLiturgics pull request #6
Opened 2018-09-05 06:07 UTC by JedBartlett

I've added the antiphon, and I think I got all your e-mail contents captured here.

2018-09-05 06:08 UTC, JedBartlett commented
[NativityTheotokos-Antiphon1-rdrG.pdf](https://github.com/JedBartlett/OrthodoxLiturgics/files/2351456/NativityTheotokos-Antiphon1-rdrG.pdf)

2018-09-06 02:19 UTC, ghost requested changes
Has a few errors but it's almost there.

2018-09-06 02:19 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-Antiphon1-rdrG.ly
> +  Re -- mem -- ber, O Lord, Dav -- id and all his meek -- ness.
Da -- vid

2018-09-06 02:19 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-Antiphon1-rdrG.ly
> +  Glo-- ri -- ous things are spo -- ken of thee,
Space after Glo

2018-09-06 02:19 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-Antiphon1-rdrG.ly
> +  God is in the midst of her; she shall not be sha -- ken;
shak -- en

2018-09-06 02:19 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-Antiphon1-rdrG.ly
> +  Glo -- ry to the \recite "Father and to the Son and to" the Ho -- ly Spi -- rit,
Spir -- it

2018-09-06 02:19 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-Antiphon1-rdrG.ly
> +  b4 c d d d e2 e4 d4 r4 \bar "|"
On "David" e2 e4 should be changed to e2. for a dotted half note

2018-09-06 02:19 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-Antiphon1-rdrG.ly
> +  g4 a b b b g a2 a4 a g2. r4 \bar "||"
Remove rest for consistency with other phrases

2018-09-06 02:19 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-Antiphon1-rdrG.ly
> +  g4 g g g g g g2 g4 g d2. r4 \bar "||"
Should move to F# on "plains", no rest at the end to stay consistent with the other phrases.
g4 g g g g g fis2 fis4 fis d2. \bar "||"

2018-09-06 02:19 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-Antiphon1-rdrG.ly
> +  b4 c d d d b c2 c4 c b2. r4 \bar "||"
Remove rest for consistency with other phrases

2018-09-06 02:19 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-Antiphon1-rdrG.ly
> +  g4 g g g g g c,2 c4 e g2. r4 \bar "||"
Should stay on a D through "plains of the", no rest for consistency.
g4 g g g g g d2 d4 d g2. \bar "||"

2018-09-06 02:19 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-Antiphon1-rdrG.ly
> +  b4 b c d d e2. c4 e d2 r4 \bar "|"
On "spoken of", moving from C to E is good for maintaining interest in the phrase, but unfortunately it causes parallel octaves with the bass, which makes it sound weird. Instead you should either stay on E or, if you want to keep an interesting phrase in the tenor here, you can make it a voice exchange with the bass by swapping the notes around, repeating the E then moving to the C and finishing on D.

So basically change the c4 e to e4 e or e4 c

2018-09-06 02:19 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-Antiphon1-rdrG.ly
> +  b4 c d d d d d d d b c e2. d4 r4 \bar "|"
On "not be", the B and C sound a bit dissonant, you probably want C and D instead. So change b c e2. to c d e2.

2018-09-06 02:19 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-Antiphon1-rdrG.ly
> +  g4 g g g g g g g g g g g2. d4 r4 \bar "|"
I would keep this phrase similar to the others by staying on the G. That way it stands out more in the refrain when the alto skips the F# straight down to D. So change g2. d4 to g2. g4

2018-09-06 05:46 UTC, JedBartlett commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-Antiphon1-rdrG.ly
> +  b4 b c d d e2. c4 e d2 r4 \bar "|"
I like the second option here, otherwise the tenor isn't adding anything to this phrase.

2018-09-06 05:48 UTC, JedBartlett commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-Antiphon1-rdrG.ly
> +  b4 c d d d d d d d b c e2. d4 r4 \bar "|"
Yea, that's what I meant, doesn't sound right at all when I play it.

2018-09-06 17:09 UTC, jbhak4 commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-Antiphon1-rdrG.ly
> +  g4 g g g g g g2 g4 g d2. r4 \bar "||"
Rest was removed, still need to change the last 3 Gs to F#s

2018-09-06 17:10 UTC, jbhak4 commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-Antiphon1-rdrG.ly
> +  g4 g g g g g g2 g4 g d2. \bar "||"
Still need to change last 3 Gs to F#s, like this:
g4 g g g g g fis2 fis4 fis d2. \bar "||"

2018-09-06 17:11 UTC, jbhak4 commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-Antiphon1-rdrG.ly
> +  b4 b c d d e2. c4 e d2 r4 \bar "|"
Yeah me too

2018-09-07 04:32 UTC, ghost approved these changes

2018-09-07 05:40 UTC, merged