First draft of NativityTheotokos Megalynarion - sop and bas only
JedBartlett/OrthodoxLiturgics pull request #8
Opened 2018-09-06 05:12 UTC by JedBartlett

Initial draft, needs to have the extra parts before merging, but wanted to get some feedback on the setting before finishing it.
(attached is a .zip with an mp3 of the midi)
[Megalynarion.zip](https://github.com/JedBartlett/OrthodoxLiturgics/files/2355509/Megalynarion.zip)

2018-09-06 18:22 UTC, ghost requested changes
Just a couple mistakes and a few phrasing things.

2018-09-06 18:22 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +    c4 b4 c2( d4 c4 b2) \bar "|"
Let's omit the reciting tone here as it's a short phrase. So it would be:
b4 (c) d % Intonation
b4 % Prep
c2 (d4) c b2 \bar "|" % Cadence

2018-09-06 18:22 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +\recite "Verily, virgini" -- ty, O The -- o -- to -- kos,
The reciting tone should end on "O", so "The-" is emphasized, like:
\recite "Verily, virginity," O The -- o -- to -- kos,

2018-09-06 18:22 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +  c\breve c4 b2 a4 c4 b2( a2) g2 \bar "|"
With the phrasing fix we will also need to slur "-o-", like
c\breve c4 b2 a4 (c) b2 (a) g \bar "|"

2018-09-06 18:22 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +    c,\breve c4 g'4( c,2) b4( c4) g'2 \bar "|"
Misplaced slur, g'4( c,2) b4( c4) should be changed to g'4 c,2 (b4 c)

2018-09-06 18:22 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +as birth -- \recite "giving is impossi" -- ble for __ vir -- gins.
Remove duration marker on the word "for"

2018-09-06 18:22 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +  b4 c\breve c4 b4 c4 c4 d4 b4 c2( b2) a1 \bar "|."
"Where-" is the accented syllable, so skip the intonation and start on c\breve. Also to match the phrasing change on "the earth do cease-", change the c4 c4 to a c2

2018-09-06 18:22 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +Where -- \recite "fore, all we families of" the earth
Start reciting on "Where-", because that's the accented syllable. Also we should emphasize "cease-" instead of "do", so end the reciting tone on "earth". Like:
\recite "Wherefore, all we families of the" earth

2018-09-06 18:22 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +    c,4 g'4 c,2( b4 c4 g'2) \bar "|"
Omit the reciting tone, so it should be:
g2 g4 % Intonation
g4 % Prep
c,2 (b4) c g'2 \bar "|" % Cadence

2018-09-06 18:22 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +  c,\breve c4 g'2 e4 c4 d2( d2) g2 \bar "|"
To slur "-o-", we should change e4 c4 to e4 (c)

2018-09-06 18:22 UTC, ghost commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +  g4 c,\breve c4 g'4 c,4 c g'4 g c,2( g2) a1 \bar "|."
Remove the intonation (the first g4) and change the c,4 c to c,2

2018-09-07 03:48 UTC, JedBartlett commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +    c4 b4 c2( d4 c4 b2) \bar "|"
That's better, I didn't like that one.

2018-09-07 03:56 UTC, JedBartlett commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +as birth -- \recite "giving is impossi" -- ble for __ vir -- gins.
Should I add one on the "as __" at the beginning?  I think it helps

2018-09-07 04:19 UTC, JedBartlett commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +  c,\breve c4 g'2 e4 c4 d2( d2) g2 \bar "|"
I miss-read this, and I now have:
![image](https://user-images.githubusercontent.com/11756408/45198247-795f9080-b21a-11e8-87ba-12590ada6249.png)
Do you think this is better?

2018-09-07 04:34 UTC, JedBartlett commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +  c,\breve c4 g'2 e4 c4 d2( d2) g2 \bar "|"
No, I don't think it's better. --- Changing it back to how you suggested.

2018-09-07 04:34 UTC, jbhak4 commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +  c,\breve c4 g'2 e4 c4 d2( d2) g2 \bar "|"
Not really, the phrase emphasizes whatever syllable is on the B half note, so having O on there de-emphasizes Theotokos too much.

2018-09-07 04:35 UTC, jbhak4 commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +as birth -- \recite "giving is impossi" -- ble for __ vir -- gins.
Sure

2018-09-07 04:45 UTC, JedBartlett commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +    c4 b4 c2( d4 c4 b2) \bar "|"
Ok, so this is what it looks like with your suggestions:
![image](https://user-images.githubusercontent.com/11756408/45198845-787c2e00-b21d-11e8-8308-fc83ad0cfd22.png)
Changeset: c2a7d651792f033752194bdf80717cb53b3cddbb

Or, drop the preface and you get: 
![image](https://user-images.githubusercontent.com/11756408/45198915-eb85a480-b21d-11e8-8f67-50dfd577d125.png)
939f06932821bac9279e1a7615e8cb4585f427bd

2018-09-07 04:57 UTC, jbhak4 commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +    c4 b4 c2( d4 c4 b2) \bar "|"
Musically, I think either works. I went with dropping the reciting tone because the rubric specifically mentions that as a possibility.

2018-09-07 05:13 UTC, jbhak4 commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
>    c,\breve c4 g'2 e4 c4 d2( d2) g2 \bar "|"
e4 c4 should be e4 (c)

2018-09-07 05:17 UTC, JedBartlett commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +    c4 b4 c2( d4 c4 b2) \bar "|"
Tatiana and I think the second one can be executed with less practice.. so we'll go with that one.

2018-09-07 05:37 UTC, jbhak4 commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
>    c,\breve c4 g'2 e4 c4 d2( d2) g2 \bar "|"
bump

2018-09-07 05:38 UTC, jbhak4 commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +  c,\breve c4 g'2 e4 c4 d2( d2) g2
e4 c4 should be e4 (c)

2018-09-07 05:40 UTC, jbhak4 commented on MusicTexts/Menaion/09-08-NativityOfTheTheotokos/NativityTheotokos-megalynarion-Kievan-rdrG.ly
> +    e\breve d4 d4 e2( f4 e4) d2
e\breve d4 should be e\breve e4

2018-09-07 05:55 UTC, ghost approved these changes

2018-09-07 05:55 UTC, merged